spring:
  cloud:
    nacos:
      #服务发现
      discovery:
        server-addr: http://nacos.yunibobo.cn
        namespace: 32d93268-bdb6-40a0-8740-a211f74b9a9f
  #redis
  redis:
    database: 0
    host: yunibobo.cn
    port: 16379
    password: myredis
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yunibobo.cn:13306/wechat_mp?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: wechat_mp
    password: wechat_mp