spring:
  cloud:
    nacos:
      #服务发现
      discovery:
        server-addr: http://nacos.yunibobo.cn
        namespace: dbe63b4c-fa43-4eb0-ab4c-7b6f3cd71c79
  #redis
  redis:
    database: 2
    host: yunibobo.cn
    port: 16379
    password:
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yunibobo.cn:13306/wechat_mp?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: wechat_mp
    password: wechat_mp