#2.3x-优雅关机
server:
  shutdown: graceful
logging:
  config: classpath:logback-spring.xml
spring:
  #v2.4x-yml改版，设置下面这个则可以继续使用以前的配置
  config:
    use-legacy-processing: true
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yunibobo.cn:13306/wechat_mp?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  #2.3x-10内优雅关机
  lifecycle:
    timeout-per-shutdown-phase: 10s
  #2.3x-时间格式化
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss
  #2.4x-修改配置
  web:
    resources:
      add-mappings: true
#mybatis
mybatis-plus:
  global-config:
    db-config:
      #主键类型
      id-type: auto
      #逻辑删除
      logic-delete-value: 0
      logic-not-delete-value: 1
  #xml位置
  mapper-locations: classpath*:mapper/**/*.xml
  #po位置
  type-aliases-package: com.cjh.common.po
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# xxl-job
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://xxl-job.yunibobo.cn/xxl-job-admin
    executor:
      ip: ''
      address: ''
      appname: xxl-job-executor-common
      logpath: /home/logs/xxl-job/common
      logretentiondays: 30
      port: 7101
domain: http://base.yunibobo.cn