server:
  port: 8056
spring:
  application:
    name: douban
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.168:8048
  redis:
    host: 192.168.1.168
    port: 6379
    database: 1
